### ISSUE TITLE
 Error in count_codons Function While Following the CUBAR Example

### ISSUE THREAD

**Issue by jhtrujillo** [mt1022/cubar#10]
Hi!

I am attempting to follow the example provided on the [CUBAR package documentation page](https://mt1022.github.io/cubar/articles/cubar.html). However, I encountered an issue when running the command:

yeast_cf <- count_codons(yeast_cds_qc)  
I received the following error:

But I got the following error:

Error in seq.default(1, nchar(sequence) - 2, by = 3) :  
  'to' must be of length 1  

It seems the issue arises from the count_codons function. Could you please help me understand what might be causing this error? Is there a specific format or preprocessing step required for the yeast_cds_qc object before passing it to count_codons?

Thank you for your assistance!

**Comment by creaturemoon** [comment]
Hi @jhtrujillo,

Thanks for using `cubar`. `count_codons` should be functional. Following the tutorial, here is a sample code using the internal dataset `yeast_cds`.
```
library(cubar)
yeast_cds_qc <- check_cds(yeast_cds)
yeast_cf <- count_codons(yeast_cds_qc)
```
Could you provide an example or execute it again in a new environment for further clarification?

You may perform quality control of sequences, such as checking and removing start or stop codons according to your needs using the function `check_cds` before calculating the occurrences of the codons using `count_codons`.
