### ISSUE TITLE
seq_to_codons not working

### ISSUE THREAD

**Issue by avvypaks** [mt1022/cubar#2]
Hello, 

Thanks for this awesome package!

I am trying to get the ENC values for a large dataset of a single gene. I am stuck in the seq_to_codons function. The error showing is 

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘XString’ for signature ‘"NULL"’

It would be great if you could please help me with this.

Thanks,

**Comment by mt1022** [comment]
Thanks for using `cubar`. `seq_to_codons` should work as far as I can see. Here is a sample code using the internal dataset `yeast_cds`, and a sample sequence in the from of a character string:
```R
> library(cubar)
> cubar::yeast_cds[[1]]
471-letter DNAString object
seq: ATGAGTTCCCGGTTTGCAAGAAGTAATGGCAATCCCAACCACATTAG...TGTTGAAATGATGGCAGTGGATACTGATGTGGATATGGATGCGTAA
> seq_to_codons(cubar::yeast_cds[[1]])
  [1] "ATG" "AGT" "TCC" "CGG" "TTT" "GCA" "AGA" "AGT" "AAT" "GGC" "AAT" "CCC" "AAC" "CAC" "ATT" "AGG"
 [17] "AAA" "AGA" "AAT" "CAT" "TCT" "CCA" "GAC" "CCA" "ATA" "GGA" "ATT" "GAT" "AAT" "TAT" "AAA" "AGA"
 [33] "AAA" "AGA" "CTA" "ATT" "ATA" "GAT" "TTA" "GAG" "AAT" "TTA" "TCC" "TTA" "AAT" "GAT" "AAA" "GGG"
 [49] "CCC" "AAG" "AAC" "GGA" "CAT" "GCA" "GAT" "GAT" "AAC" "AAT" "CTT" "ATT" "CAT" "AAC" "AAT" "ATA"
 [65] "GTA" "TTC" "ACA" "GAC" "GCT" "ATT" "GAT" "GAT" "AAG" "GTC" "CTG" "AAA" "GAG" "ATC" "ATC" "AAG"
 [81] "TGT" "TCC" "ACA" "AGT" "AAA" "CGC" "GGC" "GAC" "AAT" "GAC" "TTG" "TTT" "TAT" "GAC" "AAA" "ATA"
 [97] "TGG" "GAA" "CGT" "TTG" "AGA" "GAA" "AAA" "AGG" "CTA" "CAA" "ATA" "ATA" "AAA" "TGG" "GTA" "GAT"
[113] "TAT" "AAG" "GAA" "ATT" "GCT" "TAT" "CTA" "AGC" "TGG" "TGG" "AAG" "TGG" "TTC" "CAT" "AAT" "CAA"
[129] "ATG" "ACT" "TCG" "AAA" "TAC" "ACT" "TAT" "GAT" "GGA" "GAG" "GCT" "GAT" "ACC" "GAT" "GTT" "GAA"
[145] "ATG" "ATG" "GCA" "GTG" "GAT" "ACT" "GAT" "GTG" "GAT" "ATG" "GAT" "GCG" "TAA"
> seq_to_codons('AAATTTCCCGGG')
[1] "AAA" "TTT" "CCC" "GGG"
```
How did you use this function? Can you share a reproducible example for me to debug?

**Comment by avvypaks** [comment]
Thanks for the response. 

I have used a dataset of 10k DNA barcodes, i.e. mitochondrial COX1 sequences.
Loaded the fasta file with biostrings.

>ontdata2 <- readDNAStringSet("allont_aligned.fasta") 

But this is showing the following error now.

>cubar::ontdata2[[1]]
Error: 'ontdata2' is not an exported object from 'namespace:cubar'

FYI: the yeast_cds data is working perfectly.

Kindly help.

**Comment by mt1022** [comment]
Could you remove `cubar::` before `ontdata`? like this:

```R
library(cubar)
ontdata2 <- readDNAStringSet("allont_aligned.fasta")
seq_to_codons(ontdata2[[1]])
```

**Comment by avvypaks** [comment]
<img width="1512" alt="Screenshot 2023-11-09 at 8 40 42 PM" src="https://github.com/mt1022/cubar/assets/68179046/d6208873-21af-4972-b19d-53b94039303d">


Thank you for the reply. I am currently stuck in the next line of code. Please the attached image. 

Is check_cds working properly?

**Comment by avvypaks** [comment]
<img width="1512" alt="Screenshot 2023-11-09 at 8 44 58 PM" src="https://github.com/mt1022/cubar/assets/68179046/78ea3a82-4e14-40c3-a00f-141824523921">


Looks like cds_qc is not working for my dataset. My data is in simple fasta format. Do I need to change anything before loading the dataset?
Thanks.

**Comment by mt1022** [comment]
looks like your data is empty after QC. What's the result of `print(ont_cds_qc)`?

**Comment by avvypaks** [comment]
You are correct!
it shows:  DNAStringSet object of length 0

I have a dataset of more than 10k sequences, 669 bp each.

Can you tell me what can be the issue?

**Comment by avvypaks** [comment]
I tried with a smaller dataset now. Unfortunately, check_cds is not working there too.

**Comment by mt1022** [comment]
`check_cds` has many default qc procedures. You need to check these options and determine whether they are necessary

type `?check_cds` and you will see these lines in the help:

```
Usage
check_cds(
  seqs,
  codon_table = get_codon_table(),
  min_len = 6,
  check_len = TRUE,
  check_start = TRUE,
  check_stop = TRUE,
  check_istop = TRUE,
  rm_start = TRUE,
  rm_stop = TRUE,
  start_codons = c("ATG")
)
Arguments
seqs	
input CDS sequences

codon_table	
codon table matching the genetic code of seqs

min_len	
minimum CDS length in nt

check_len	
check whether CDS length is divisible by 3

check_start	
check whether CDSs have start codons

check_stop	
check whether CDSs have stop codons

check_istop	
check internal stop codons

rm_start	
whether to remove start codons

rm_stop	
whether to remove stop codons

start_codons	
vector of start codons
```

For example, if your data does not have stop codon, you should use:
```R
ont_cds_qc <- check_cds(ontdata2, codon_table = get_codon_table(gcid = '2'), check_stop = F, rm_stop = F)
```

**Comment by mt1022** [comment]
Besides, you also need to specify start codons possible for your dataset with the `start_codons=` parameter of `cubar`. As the mitochondrial start codons [depend on the organism you are analyzing](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG2), `cubar` cannot determine it automatically.

**Comment by avvypaks** [comment]
Thank you so much. It's working now with the following customization.

ont_cds_qc <- check_cds(
  ontdata,
  codon_table = get_codon_table("5"),
  check_len = FALSE,
  check_start = FALSE,
  check_stop = FALSE,
  check_istop = FALSE,
  rm_start = FALSE,
  rm_stop = FALSE,
)


Yes. I have changed the codon table to 5, as I am working with insects. Let me know if I am correct.

**Comment by mt1022** [comment]
I would suggest setting `check_len = TRUE, check_istop = TRUE` at least when using `check_cds`. If most sequences are excluded by length and internal stop codon checking, your input sequences might be problematic. If you do not need QC procedures implemented in `check_cds`, you can just skip this step and do custom QC manually.

**Comment by avvypaks** [comment]
Ok. That also works.

Thank you so much for the package and the support!

Cheers.
